url=https://demo.guru99.com/test/newtours/
password.field.name=password
username.field.name=userName
login.button.name=submit
expected.login.title=Welcome: Mercury Tours
expected.login.success=Login Successfully
expected.error.title=Welcome: Mercury Tours
expected.login.failed=Login failed
testExecutionKey=TES-5
